name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: yarn
      - name: Typescript check
        run: yarn tsc
      - name: Run tests
        run: yarn test
        env:
          VITE_NETWORK: amoy
      - name: Run lint
        run: yarn lint
