# Example Portal Deploy
name: Portal deploy (Mine Whack)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: portal-deploy-mine-whack
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

      - name: Get the current version ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_SHA}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
          CI: false
          VITE_NETWORK: "amoy"
          VITE_CLIENT_VERSION: ${{ steps.date.outputs.date }}
          VITE_PRIVATE_IMAGE_URL: "https://sunflower-land.com/testnet-assets"
          VITE_API_URL: "https://api-dev.sunflower-land.com"
          VITE_ROOM_URL: "wss://216-238-112-132.colyseus.dev/"
          VITE_ANIMATION_URL: "https://animations-dev.sunflower-land.com"
          VITE_PORTAL_APP: "mine-whack"
          VITE_PORTAL_GAME_URL: "https://sunflower-land.com/testnet/"
          VITE_PORTAL_DONATION_ADDRESS: "0x7032d77dAa4DCecFBBDa6eED18fD11D8b5C33C48"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PORTAL_DEPLOY_ACCESS_KEY_MINE_WHACK }}
          aws-secret-access-key: ${{ secrets.PORTAL_DEPLOY_SECRET_MINE_WHACK }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 subdomain
        run: aws s3 sync ./dist/ s3://mine-whack.sunflower-land.com/ --delete
