name: Translate

on:
  push:
    branches:
      - main
    paths:
      - src/lib/i18n/dictionaries/dictionary.json

jobs:
  translate:
    runs-on: ubuntu-latest
    environment: develop
    concurrency: testnet-translate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRANSLATOR_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run translation script
        run: yarn translate

      - name: Configure Git user
        run: |
          git config --global user.name "Translator Bot"
          git config --global user.email "translator@sunflower-land.com"

      - name: Pull latest changes
        run: |
          git fetch origin
          git pull origin main

      - uses: EndBug/add-and-commit@v9
        with:
          message: "[BOT] Update translations [skip ci]"
          committer_name: Translator Bot
          committer_email: translator@sunflower-land.com
          add: src/lib/i18n/dictionaries/*.json
          commit: --no-verify
